### ISSUE TITLE
Outline OKRs and KPIs

### ISSUE THREAD

**Issue by ArsalaBangash** [grey-software/open-local-governance#17]
# Strategy

Leverage modern technologies to reform the government's fee collection pipeline. 

# Goals

#### 2) Introduce citizens to a method to pay the government that is:
- Simple
- Accessible
- Fast
- Secure

#### 3) Introduce government staff to modern methods and tools

# Goal Details
### 1) 
Currently, a collector is responsible for collecting fees from the citizen to the government, allowing for corruption. Our solution mitigates the need for middlemen in the fee collection pipeline while providing an immutable audit trail to track and reduce illegitimate transactions.

### 2) 
Our solution begins with allowing citizens to directly pay the government through a mobile application that leverages Pakistan's major phone-banking solutions. 

### 3) 
Our solution includes a dashboard that allows government staff to monitor payment statistics at a glance. The ERP component will supply the government with accurate information that will allow the government to respond to changes, make key strategic decisions, and plan for the future.  

# KPIs

### KPI relating to the first goal are:
    a) Increase user app adoption for individuals transacting with the government
    b) Decrease the aggregate number of missing payments within the Government's jurisdiction
    c) Increase number of returning users

How much money does the government expect to receive per month?

### For the second goal, the KPIs are:
    a) Decrease the length of time for the user to determine what fees they need to pay, and pay it.
    b) Decrease the length of time needed for returning users to log in to their account.
    c) Decrease the setup time for first-time users.

Security, how long should passwords be, what security features should be offered to the citizen? 

### For the third goal, the KPIs are:
    a) Decrease the length of time the government user needs to find and access, the information required to take action
    b) Increase the number of actionable information the government user can access.
    c) Decrease the length of time the government user needs to relate the information to what action they need to take.
    d) Decrease the length of time required by the government user needs to gauge payment performance. 

# Targets

- Increase the number of users making transactions to the government. The target can be taken as a percentage of the total number of citizens liable to pay fees. 

- Decrease the number of missing payments. Can be taken relative to the expected number of payments or payment volume. Ex. Current system missing % of total number/total volume/total user payments, solution decrease to % missing. 

- Increase the number of returning users. Target will be to achieve at least x% user retention (Should aim for 100% or else solution fails to work)

- Decrease the length of time for the user to determine what fees they need to pay, and pay it. Users should be able to glance at their account dashboard and clearly see what fees are due.

- Decrease the length of time needed for returning users to log in to their account. Users ideally can log in less than a minute. 

- Decrease the setup time for first-time users. Users should be able to set up their account after giving their phone number + additional security details. Should take less than 5 minutes. 

# Key Success Factors

- [ ] PWA can send payment requests to users. 

- [ ] PWA can receive payments from various popular payment processors.

- [ ] PWA can track citizen by phone number (Connect to government ID).

- [ ] Alerts for overdue fees can be easily seen and paid by citizens (citizen's side).

- [ ] Real-time data visualization for fee payments (gov. side). 

- [ ] Data/transaction storage for long term monitoring (gov. side).

**Comment by ayu2234** [comment]
KPI b) and c) for 3rd goal should be combined in a)

**Comment by ArsalaBangash** [comment]
Moved to an MD file in the repo

**Comment by ShabazBadshah** [comment]
Added OKRs and KPIs to Github [wiki](https://github.com/grey-software/open-local-governance/wiki/OKRs-and-KPI)
