### ISSUE TITLE
Questions to Ask 12/7/20

### ISSUE THREAD

**Issue by ayu2234** [grey-software/open-local-governance#18]
# Potential Questions to Ask Government

### What's the period of time the government expects payment to be completed in?
- Example: Canada requires the filing of taxes yearly
- Are there fees of fixed amounts occurring regularly? Like a subscription-based fee system. 

### How does the government currently keep records of who needs to pay what fees?
- If so, how many people are expected to use the app?
- Required to actually automate the process of sending fees to citizens/users.
- Is it possible to fully digitize the records such that the above feature can be implemented?

### Does the government currently keep records regarding who hasn't paid/how many fees haven't been paid?
- What is the number of users who need to pay fees, and what percentage of users who don't pay the fees? Why don't they pay?

### What is the type of fee that is most frequently missed?
- Is it a variable fee or a fixed fee? (Variable dependent on user actions, fixed are fees of the same amount every pay period)
- Reasons why it's most commonly missed?

### What are some functionalities the government would like? (In regards to what decisions require knowing details of collected fees.)
- Would the government like having a feature displaying predicted fees collected in some period in the future?
- What are some decisions made that are based on the fees collected? An example would be how they decide to accept or reject project proposals, which could be based on capital available which can be based largely on the fees collected/predicted fees collected.

### What are some key strategic decisions or planning decisions made based on fees collected?
- What are the current issues arising from missing collected fees and how can we resolve the issues using data on the user transactions?

### How can we make this app more valuable to the government?
- Aside from just collecting the fee, what else can we offer to make them use our app?
- Do they want functionality for tracking citizens? Do they want functionalities to predict future payments? Do they want the information to make decisions for the future? If so, what additional features are required?
- What are some things currently done by hand that we can also digitize and automate? Ex. Calculating how much they have left over after expenses, calculating budgets, etc.

**Comment by ArsalaBangash** [comment]
Updated questions for the magistrate: 

## What's the period of time the government expects payment to be completed in?
- Example: Canada requires the filing of taxes yearly
- Are there fees of fixed amounts occurring weekly or monthly?

## How does the government currently keep records of who needs to pay what fees?

- If so, how many people are expected to use the app?
- Required to actually automate the process of sending fees to citizens/users.
- Is it possible to fully digitize the records such that the above feature can be implemented?

## Does the government currently keep records regarding who hasn't paid/how many fees haven't been paid?
- What is the number of users who need to pay fees, and what percentage of users who don't pay the fees? Why don't they pay?
Does the government have an expected amount per payment period?
What is the type of fee that is most frequently missed?
- Is it a variable fee or a fixed fee? (Variable dependent on user actions, fixed are fees of the same amount every pay period)
- Reasons why it's most commonly missed?

## What are some functionalities the government would like with respect to knowing details of collected fees.
- Who makes the key strategic decisions or planning decisions made based on fees collected?
- What are the current issues arising from missing collected fees and how can we resolve the issues using data on the user transactions?

## How can we make this app more valuable to the government?
- Aside from just collecting the fee, what else can we offer to make them use our app?
- What are some things currently done by hand that we can also digitize and automate?
