### ISSUE TITLE
User Personas and Segment 

### ISSUE THREAD

**Issue by ayu2234** [grey-software/open-local-governance#19]
## Citizens Side
- Users who want access to government services and want to fund projects directly.
    - User who must stand in line at banks and wait for excessive amounts of time to make transactions to the government. 
- Users who are satisfied regarding wealth, and want infrastructure around them.
    - Real estate investors, people who are invested in the land will want to see cleaner streets.
- Users who can give constructive feedback regarding what they want to see.
- Users who are aware of corruption in the current system and want change.
- Users who live in areas not serviced by the government and are willing to pay for services. 
## Governments Side
- Users who are aware of current digital solutions.
- Users who value data in decision-making process.
- Users who realize corruption in the system and want change.
- The collector whos role is being disrupted.
- Clerical staff who may have workload lifted.

**Comment by ArsalaBangash** [comment]
I put this up on a markdown file on our repo!
